function dUde = calc_dUde(l1,q1)
%CALC_DUDE
%    DUDE = CALC_DUDE(L1,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    30-Mar-2020 20:27:28

dUde = reshape([-l1.*sin(q1),l1.*cos(q1),0.0,0.0],[2,2]);
